---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: python-checks
  pull: always
  image: python
  commands:
    - pip install black prospector[with_bandit]
    - pip install -r requirements.txt
    - prospector --with-tool bandit main.py
    - black --check main.py

- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: dronenotify-dev

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    from: dronenotify-dev
    repo: adamant/drone-notify
    tags:
    - latest
    - "%label org.label-schema.version"
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
    - push
    - tag
---
kind: signature
hmac: f58e6ca912aeded5fcbe8b7a5c55c538e5ced0ac1866f7de5cf26bbc6cae6a13

...
